In [54]:
import numpy as np

In [49]:
print("Задача 1.  Выполнить оперции над матрицами:\n")
A = np.matrix([[1, 2, 1],
               [-2, 1, 1]])
B = np.matrix([[3, 1],
               [-1, 0],
               [2, 4]])
C = np.matrix([[-2, 2],
               [1, -1],
               [1, 2]])
print(f'{"A=":^5} \n {A} \n')
print(f'{"B=":^5} \n {B} \n')
print(f'{"C=":^5} \n {C} \n')
print("Сложение (A+2*B) выполнить невозможно, поскольку матрицы разных размеров.\n")

A = np.transpose(A).reshape(3,2)
print("После транспонирования матрица A имеет вид:\n", A, \n')
print(f'{"Первое выражение A+2*B:":^5} \n {A+2*B} \n')
print(f'{"Второе выражение B+2*C:":^5} \n {B+2*C} \n')

Задача 1.  Выполнить оперции над матрицами:

 A=   
 [[ 1  2  1]
 [-2  1  1]] 

 B=   
 [[ 3  1]
 [-1  0]
 [ 2  4]] 

 C=   
 [[-2  2]
 [ 1 -1]
 [ 1  2]] 

Сложение (A+2*B) выполнить невозможно, поскольку матрицы разных размеров.

После транспонирования матрица A имеет вид:
 [[ 1 -2]
 [ 2  1]
 [ 1  1]]
Первое выражение A+2*B: 
 [[7 0]
 [0 1]
 [5 9]] 

Второе выражение B+2*C: 
 [[-1  5]
 [ 1 -2]
 [ 4  8]] 



In [50]:
print("Задача 2:  Создать матрицу размером 8х8 элементов, состоящую из нулей.\n")
matrix_01 = np.zeros((8,8), dtype = int)
matrix_01[1::2, ::2] = 1
matrix_01[::2, 1::2] = 1
print("matrix_01:\n", matrix_01)

Задача 2:  Создать матрицу размером 8х8 элементов, состоящую из нулей.

matrix_01:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [65]:
print("Задача 3: Сформировать два вектора.\n")

vec01 = np.arange(0, 1.5, 0.1, dtype = float)
vec02 = np.arange(1, 7, 1)
print(f'{"Вектор 1 имеет вид:":^5} \n {vec01} \n')
print(f'{"Вектор 2 имеет вид:":^5} \n {vec02} \n')

matrix_01 = vec01.reshape(5,3)
matrix_02 = vec02.reshape(3, 2)
print(f'{"matrix_01:":^5} \n {matrix_01} \n')
print(f'{"matrix_02:":^5} \n {matrix_02} \n')
print("Произведение matrix_01*matrix_02 нельзя найти, поскольку число столбцов матрицы matrix_01 не равно числу строк matrix_02.\n")

matrix_03 = np.zeros((3,3), dtype = int)
matrix_04 = np.hstack((matrix_02, matrix_03))
matrix_05 = np.dot(matrix_01, matrix_04)
print("matrix_03: \n", matrix_03, "\n")
print("matrix_04: \n", matrix_04, "\n")
print("Произведение matrix_01, matrix_04: \n", matrix_05, "\n")


matrix_06 = np.delete(matrix_05, np.s_[2:], 1)
print("matrix_06: \n", matrix_06, "\n")

Задача 3: Сформировать два вектора.

Вектор 1 имеет вид: 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4] 

Вектор 2 имеет вид: 
 [1 2 3 4 5 6] 

matrix_01: 
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]] 

matrix_02: 
 [[1 2]
 [3 4]
 [5 6]] 

Произведение matrix_01*matrix_02 нельзя найти, поскольку число столбцов матрицы matrix_01 не равно числу строк matrix_02.

matrix_03: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]] 

matrix_04: 
 [[1 2 0 0 0]
 [3 4 0 0 0]
 [5 6 0 0 0]] 

Произведение matrix_01, matrix_04: 
 [[ 1.3  1.6  0.   0.   0. ]
 [ 4.   5.2  0.   0.   0. ]
 [ 6.7  8.8  0.   0.   0. ]
 [ 9.4 12.4  0.   0.   0. ]
 [12.1 16.   0.   0.   0. ]] 

matrix_06: 
 [[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]] 



In [67]:
print("Задача 4: Сформировать вектор из целых чисел размерностью 36.\n")

vec05 = np.arange(1, 36 , 2, dtype='int32')
vec06 = [i for i in vec05 if i%3==0]
print("Верктор размерносью 36: \n", vec05, "\n")
print("Вектор с элементами кратные 3: \n", vec06)

Задача 4: Сформировать вектор из целых чисел размерностью 36.

Верктор размерносью 36: 
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35] 

Вектор с элементами кратные 3: 
 [3, 9, 15, 21, 27, 33]
